
### Get cinemas # Baza nie zawiera seansów
GET http://localhost:8085/api/showtimes


### Get cinemas # nie ma kin
GET http://localhost:8085/api/cinemas

### Get cinema showtimes # pobranie z kina które nie istnieje daje 404
GET http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6/showtimes


### Put cinema # wprowadzam pierwsze kino
PUT http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6
Content-Type: application/json

{
  "name": "Krewetka",
  "street": "Karmelicka 1",
  "city": "Gdansk",
  "zipCode": "80-200",
  "employeesNumber": 10,
  "phoneNumber": "123-456-7890",
  "openingDate": "2023-01-01"
}


### Put another cinema # wprowadzam drugie kino
PUT http://localhost:8085/api/cinemas/9d73f7ed-ac6c-4d3d-a6b1-2d262161aecd
Content-Type: application/json

{
  "name": "Helios",
  "street": "Wajdeloty",
  "city": "Gdansk",
  "zipCode": "80-205",
  "employeesNumber": 20,
  "phoneNumber": "333-456-7890",
  "openingDate": "2023-01-02"
}

### Get cinema showtimes # pobranie listy seansow z pustego kina daje pusta liste
GET http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6/showtimes

### Put showtime to cinema1
PUT http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6/showtimes/1779c893-18b9-4034-a70c-90ffdcff08ae
Content-Type: application/json

{
  "movieTitle": "Godzilla",
  "showRoomName": "Big Hall",
  "ticketPrice": 19.99,
  "numberOfTickets": 100,
  "screeningTime": "2019-02-05T22:08:28.097832"
}

### Put showtime 2 to cinema1
PUT http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6/showtimes/47fb6884-d518-4986-924a-83e23f4bb3df
Content-Type: application/json

{
  "movieTitle": "Alien",
  "showRoomName": "Small Hall",
  "ticketPrice": 9.99,
  "numberOfTickets": 50,
  "screeningTime": "2019-01-03T22:08:28.097832"
}


### Put showtime 3 to cinema2
PUT http://localhost:8085/api/cinemas/9d73f7ed-ac6c-4d3d-a6b1-2d262161aecd/showtimes/f3c10d6f-c254-48a3-b402-48391e343ea3
Content-Type: application/json

{
  "movieTitle": "Predator",
  "showRoomName": "Big Hall",
  "ticketPrice": 99.99,
  "numberOfTickets": 20,
  "screeningTime": "2023-12-03T22:08:28.097832"
}

### Get cinema showtimes # pobranie listy seansow z kina1 zwraca liste seansow
GET http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6/showtimes

### Get cinema showtimes # pobranie listy seansow z kina2 zwraca liste seansow
GET http://localhost:8085/api/cinemas/9d73f7ed-ac6c-4d3d-a6b1-2d262161aecd/showtimes

### Get cinema showtimes # sprawdzenie listy seansow
GET http://localhost:8085/api/showtimes

### Delete a cinema existing
## 200 if exists
## 404 if there is none
DELETE http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6

### Get cinema showtimes # sprawdzenie efektu kaskadowego
GET http://localhost:8085/api/showtimes