# Cinemas Endpoints
#### Get all cinemas
## always works - returns empty list of no cinemas present
GET http://localhost:8085/api/cinemas

#### Get single existing cinema
## should return an existing cinema
GET http://localhost:8085/api/cinemas/fe1ad570-dfeb-4c3f-be69-b594c0dd4fff

#### Get single non existing cinema
## should return error 404 and information that cinema does not exist
GET http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6

### Create a new cinema
## should inform that it was successful 201 Created
## if there was already a cinema 200 OK
PUT http://cinema-showtime-gateway:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc5
Content-Type: application/json

{
  "name": "Cinema Name",
  "street": "Cinema Street",
  "city": "Cinema City",
  "zipCode": "12345",
  "employeesNumber": 10,
  "phoneNumber": "123-456-7890",
  "openingDate": "2023-01-01"
}


### Delete a cinema existing
## 200 if exists
## 404 if there is none
DELETE http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6

### Delete a cinema non existing
## 200 if exists
## 404 if there is none
DELETE http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc5

# Showtimes Endpoints
#### Get showtimes for a cinema
GET http://localhost:8085/api/cinemas/fe1ad570-dfeb-4c3f-be69-b594c0dd4fff/showtimes

#### Delete cinema with cascade showtimes
DELETE http://localhost:8085/api/cinemas/fe1ad570-dfeb-4c3f-be69-b594c0dd4fff

#### Get existing showtime
GET http://localhost:8085/api/cinemas/fe1ad570-dfeb-4c3f-be69-b594c0dd4fff/showtimes

#### Get showtimes for a non existing cinema
GET http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc5/showtimes

### Get all showtimes
GET http://localhost:8085/api/showtimes

### Get single showtime (showtime exists)
GET http://localhost:8085/api/showtimes/c60bb33b-cca3-4325-9a73-febc771e5c0e

### Get single showtime (showtime does not exist)
GET http://localhost:8085/api/showtimes/b5d6e3db-aa5c-4724-8409-3c42a914dc98

### Delete a non existing showtime
DELETE http://localhost:8085/api/showtimes/b5d6e3db-aa5c-4724-8409-3c42a914dc98

### Delete an existing showtime
DELETE http://localhost:8085/api/showtimes/c60bb33b-cca3-4325-9a73-febc771e5c0e

### Get existing showtimes from one cinema
GET http://localhost:8085/api/cinemas/fe1ad570-dfeb-4c3f-be69-b594c0dd4fff/showtimes

### Get showtimes from existing cinema without showtimes
#TODO BŁĘDNE DZIAŁANIE
GET http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6/showtimes

### Get showtimes from non existing cinema
GET http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc7/showtimes

### Get cinema showtimes
GET http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6/showtimes