version: '3'

services:

  cinema-showtime-discovery:
    image: cinema-showtime-discovery:0.0.1-SNAPSHOT
    restart: always
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://cinema-showtime-discovery:8080/eureka/"

  showtime_db:
    container_name: "showtimes-db"
    image: postgres
    volumes:
      - /c/postgres/showtimes:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_DB: "showtimes"
      POSTGRES_PASSWORD: "admin"

  showtimes:
    image: showtimes:0.0.1-SNAPSHOT
    restart: always
    deploy:
      mode: replicated
      replicas: 2
    environment:
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://showtime_db:5432/showtimes"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://cinema-showtime-discovery:8080/eureka/"
      SPRING_JPA_GENERATE-DDL: "false"

  cinema_db:
    container_name: "cinemas-db"
    image: postgres
    volumes:
      - /c/postgres/cinemas:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_DB: "cinemas"
      POSTGRES_PASSWORD: "admin"

  cinemas:
    image: cinemas:0.0.1-SNAPSHOT
    restart: always
    deploy:
      mode: replicated
      replicas: 2
    environment:
      ISA_SHOWTIME_URL: "http://showtimesservice"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://cinema_db:5432/cinemas"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://cinema-showtime-discovery:8080/eureka/"
      SPRING_JPA_GENERATE-DDL: "false"

  cinema-showtime-gateway:
    image: cinema-showtime-gateway:0.0.1-SNAPSHOT
    restart: always
    environment:
      ISA_CINEMA_URL: "lb://CINEMASSERVICE"
      ISA_SHOWTIME_URL: "lb://SHOWTIMESSERVICE"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://cinema-showtime-discovery:8080/eureka/"
    ports:
      - "8085:8085"

  angularclient:
    image: angularclient:0.0.1-SNAPSHOT
    restart: always
    environment:
      API_URL: http://cinema-showtime-gateway:8085/api
    ports:
      - "8087:80"

