### Get all cinemas

GET http://localhost:8080/api/cinemas

### Get single cinema

GET http://localhost:8080/api/cinemas/47a9767c-9203-11ee-b9d1-0242ac120002

### Get single cinema not existing

GET http://localhost:8080/api/cinemas/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

### Post single cinema

POST http://localhost:8080/api/cinemas/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

### Delete single cinema

DELETE http://localhost:8080/api/cinemas/47a9767c-9203-11ee-b9d1-0242ac120002