# Cinemas Endpoints
### Create a new cinema
## should inform that it was successful 201 Created
## if there was already a cinema 200 OK
POST http://localhost:8082/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6

### Delete a cinema existing
## 200 if exists
## 404 if there is none
DELETE http://localhost:8082/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6

### Delete a cinema non existing
## 200 if exists
## 404 if there is none
DELETE http://localhost:8082/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc5

# Showtimes Endpoints
#### Get showtimes for a cinema
GET http://localhost:8082/api/cinemas/fe1ad570-dfeb-4c3f-be69-b594c0dd4fff/showtimes

####TODO THIS IS BROKEN AND NEED TO BE FIXED
#### Delete cinema with cascade showtimes
DELETE http://localhost:8082/api/cinemas/fe1ad570-dfeb-4c3f-be69-b594c0dd4fff

#### Get showtimes for a non existing cinema
GET http://localhost:8082/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc5/showtimes

### Get all showtimes
GET http://localhost:8082/api/showtimes

### Get single showtime (showtime exists)
GET http://localhost:8082/api/showtimes/c60bb33b-cca3-4325-9a73-febc771e5c0e

### Get single showtime (showtime does not exist)
GET http://localhost:8082/api/showtimes/b5d6e3db-aa5c-4724-8409-3c42a914dc98

### Delete a non existing showtime
DELETE http://localhost:8082/api/showtimes/b5d6e3db-aa5c-4724-8409-3c42a914dc98

### Delete an existing showtime
DELETE http://localhost:8082/api/showtimes/c60bb33b-cca3-4325-9a73-febc771e5c0e

### Get existing showtimes from one cinema
GET http://localhost:8082/api/cinemas/fe1ad570-dfeb-4c3f-be69-b594c0dd4fff/showtimes

### Get showtimes from existing cinema without showtimes
GET http://localhost:8082/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6/showtimes

### Get showtimes from non existing cinema
GET http://localhost:8082/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc7/showtimes

### Put showtime from non existing cinema
PUT http://localhost:8085/api/cinemas/1318ad0e-d021-4662-b962-6d419459cfc6/showtimes/c60bb33b-cca3-4325-9a73-febc771e5c0e
Content-Type: application/json

{
  "movieTitle": "Cinema Name",
  "showRoomName": "Cinema Street",
  "ticketPrice": "10.99",
  "numberOfTickets":  10,
  "screeningTime": null
}
### ^^^^^^^^^^^^^^^^^ napraw nulla mordo
